### ISSUE TITLE
ImageNet_CIFAR100 - Found no valid file for the classes

### ISSUE THREAD

**Issue by zhixiongzh** [mmazeika/model-stealing-defenses#5]
Hi,

in the provided data, Imagenet_cifar100(maybe also in other imagenet_dataset), it seems some classes are missing in the folder, which leads to such an error:

`FileNotFoundError: Found no valid file for the classes 02_baby, 11_boy, 18_caterpillar, 19_cattle, 23_cloud, 26_crab, 30_dolphin, 32_flatfish, 33_forest, 35_girl, 37_house, 46_man, 47_maple_tree, 49_mountain, 52_oak_tree, 54_orchid, 56_palm_tree, 57_pear, 59_pine_tree, 60_plain, 62_poppy, 64_possum, 66_raccoon, 68_road, 70_rose, 72_seal, 74_shrew, 76_skyscraper, 82_sunflower, 91_trout, 92_tulip, 96_willow_tree, 98_woman. Supported extensions are: .jpg, .jpeg, .png, .ppm, .bmp, .pgm, .tif, .tiff, .webp`

Could I ask how you deal with it? By deleting these mentioned folders?

**Comment by mmazeika** [comment]
Hello,

The empty folders are intentional; not all CIFAR-100 classes have corresponding classes in ImageNet. The idea is to skip over the empty classes so that the labels returned by __getitem__ correspond to the CIFAR-100 labels. Simply removing the folders would not work.

I don't remember exactly how I got around this error, but one way that works is to comment out the "raise FileNotFoundError(msg)" error in my torchvision [DatasetLoader class](https://pytorch.org/vision/main/_modules/torchvision/datasets/folder.html#DatasetFolder). You can find your torchvision install with torchvision.__path__ and directly edit the file to remove this error message, and the labels returned by __getitem__ will be aligned with CIFAR-100 labels.
